# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce909f730668ff62ee4ddc6854e9e67b26475bb1715b3fcf44d4dd35814ad4bcba736095a772783b743da9d4606344c77ea0c228febc72abca3bca6e30c6bc6

test:
  secret_key_base: 2dd0745fe8b68abdb66d1643095f38893ac456e8dd39288fa08b53962dc14ac688c796002a76b5da6608204a520d6fb8c83d805bb5dbec41d26764c81d5102a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
